apiVersion: apps/v1
kind: Deployment
metadata:
  name: ski-station-deployment
spec:
  replicas: 2 # Number of pods
  selector:
    matchLabels:
      app: ski-station
  template:
    metadata:
      labels:
        app: ski-station
    spec:
      containers:
      - name: ski-station
        image: mariemcheikhbrahim/mariemproject:latest # Docker image pushed to Docker Hub
        ports:
        - containerPort: 8080 # Port exposed by the application inside the container
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m" # Optional Java options
