apiVersion: v1
kind: Service
metadata:
  name: ski-station-service
spec:
  selector:
    app: ski-station
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the service
    targetPort: 8080 # Port in the container
  type: LoadBalancer # Exposes the service externally