- name: Deploy Docker container with Ansible
  hosts: servers
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker Image
      command: >
        docker pull mariemcheikhbrahim/mariemproject:latest

    - name: Stop existing container (if any)
      command: >
        docker stop mariemproject || true
      ignore_errors: yes

    - name: Remove existing container (if any)
      command: >
        docker rm mariemproject || true
      ignore_errors: yes

    - name: Run Docker Container
      command: >
        docker run -d --name mariemproject -p 9090:8080 mariemcheikhbrahim/mariemproject:latest